# Generated by Django 5.2.17 on 2026-10-02 17:35

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(default=60, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(1440)]),
        ),
        migrations.AddField(
            model_name='tournament',
            name='venue_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='tournament',
            name='venue_fee_status',
            field=models.CharField(choices=[('not_required', 'Not required'), ('pending', 'Pending booking cost'), ('agreed', 'Agreed cost'), ('paid', 'Marked paid'), ('waived', 'Waived')], default='pending', max_length=12),
        ),
        migrations.AddField(
            model_name='tournament',
            name='venue_pricing_type_snapshot',
            field=models.CharField(choices=[('free', 'Free'), ('fixed', 'Fixed price'), ('hourly', 'Hourly'), ('quote', 'Contact for price')], default='free', max_length=12),
        ),
        migrations.AddField(
            model_name='tournament',
            name='venue_rate_currency_snapshot',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='tournament',
            name='venue_rate_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='price_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='price_currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='venue',
            name='pricing_type',
            field=models.CharField(choices=[('free', 'Free'), ('fixed', 'Fixed price'), ('hourly', 'Hourly'), ('quote', 'Contact for price')], default='free', max_length=12),
        ),
    ]
