# Generated by Django 5.2.17 on 2026-10-02 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_tournament_duration_minutes_tournament_venue_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='tournament',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tournaments', to='tournaments.country'),
        ),
        migrations.AddField(
            model_name='venue',
            name='country_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='venues', to='tournaments.country'),
        ),
        migrations.CreateModel(
            name='CountryCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_options', to='tournaments.country')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='country_options', to='tournaments.currency')),
            ],
            options={
                'ordering': ['-is_default', 'currency__code'],
            },
        ),
        migrations.AddField(
            model_name='country',
            name='currencies',
            field=models.ManyToManyField(related_name='countries', through='tournaments.CountryCurrency', to='tournaments.currency'),
        ),
        migrations.AddField(
            model_name='country',
            name='default_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_for_countries', to='tournaments.currency'),
        ),
        migrations.AddConstraint(
            model_name='countrycurrency',
            constraint=models.UniqueConstraint(fields=('country', 'currency'), name='unique_currency_per_country'),
        ),
        migrations.AddConstraint(
            model_name='countrycurrency',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('country',), name='one_default_currency_per_country'),
        ),
    ]
