# Generated by Django 5.2.17 on 2026-10-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_playerprofile_tournamentmessage_tournamentreport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentwaitlist',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
