# Generated by Django 5.2.17 on 2026-10-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_tournamentwaitlist_notified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
